export const SETLIST = 'cart/setList'
export const ADDCART = 'cart/addCart'
export const PLUSNUM = 'cart/plusNum'
export const MININUM = 'cart/miniNum'
export const PLUS = 'cart/plus'
export const MINI = 'cart/mini'
export const DELETE = 'cart/delete'
export const DELETEONE = 'cart/deleteOne'